// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' as foundation;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static String _requiredEnv(String name) {
    const values = <String, String>{
      'FIREBASE_WEB_API_KEY': String.fromEnvironment('FIREBASE_WEB_API_KEY'),
      'FIREBASE_ANDROID_API_KEY': String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    };
    final value = values[name] ?? '';
    if (value.trim().isEmpty) {
      throw StateError('Missing required dart-define: $name');
    }
    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (foundation.kIsWeb) {
      return web;
    }
    switch (foundation.defaultTargetPlatform) {
      case foundation.TargetPlatform.android:
        return android;
      case foundation.TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case foundation.TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case foundation.TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case foundation.TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_WEB_API_KEY'),
    appId: '1:384970345898:web:bc23c9dd6245e603f46fd3',
    messagingSenderId: '384970345898',
    projectId: 'respect-app-dbc77',
    authDomain: 'respect-app-dbc77.firebaseapp.com',
    storageBucket: 'respect-app-dbc77.firebasestorage.app',
    measurementId: 'G-DY7T4DTGG3',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_ANDROID_API_KEY'),
    appId: '1:384970345898:android:05bc6f2383c6a818f46fd3',
    messagingSenderId: '384970345898',
    projectId: 'respect-app-dbc77',
    storageBucket: 'respect-app-dbc77.firebasestorage.app',
  );
}
